### ISSUE TITLE
Create basic web interface

### ISSUE THREAD

**Issue by irl** [Jaminy/GSoC#26]
Using Python Flask, create a web interface to display a list of extracted contact email addresses, and each one links to a page which contains a list of names used (probably only one name) and other extracted information (phone numbers, XMPP addresses, SIP addresses or ham callsigns).

There is no need for the web interface to have any web-based configuration, this can all happen from a configuration file (or even just hardcoded values in the script at the start of the file).

**Comment by irl** [comment]
I've implemented a skeleton for this in #34. Once you've merged this, you'll be able to add the extracted phone numbers, XMPP and SIP addresses and ham callsigns to the contact pages. Once you've done this, you'll be able to close this issue.

This needs to be integrated into the application, not just a code snippet implementing the functionality without integration.

**Comment by irl** [comment]
Sorry, I can't see the code integrated for phone numbers, XMPP/SIP addresses or ham callsigns in the web interface. This is not done yet.

**Comment by Jaminy** [comment]
For phone numbers https://github.com/Jaminy/Email-Mining/blob/master/Snippets/PN.py
And for XMPP/SIP addresses,
sip = re.findall(r'\d+', 'sip:1-999-123-4567@voip-provider.example.net').

**Comment by irl** [comment]
Yep, you have the code for finding these, but you haven't integrated this code into the web application. For each contact there should be a list of discovered numbers and addresses from the emails.

**Comment by Jaminy** [comment]
I have made changes there...what do you mean by adding to the contact pages?Is it CSV file?

**Comment by irl** [comment]
I mean, list them in the HTML output.

For each contact, which is a key in the dictionary, add an array of phonenumbers and when phone numbers are discovered in the body of the email, you can add them to this array.

In the HTML template for contacts, you can then create an HTML list of the discovered phone numbers with hyperlinks to tel: URLs.

**Comment by Jaminy** [comment]
Checkout #36 , #37 , #38 for merging.
I didn't include for SIP and XMPP addresses since I am facing problem in installing ipython.
$ sudo apt-get install ipython
import re

This include the functions to search for characters.
