### ISSUE TITLE
Add Gravatars to the detail page

### ISSUE THREAD

**Issue by irl** [Jaminy/GSoC#27]
On the page listing details for each email address, add a gravatar. This should be relatively easy:

https://secure.gravatar.com/site/implement/images/python/

**Comment by Jaminy** [comment]
https://github.com/Jaminy/Email-Mining/blob/master/Avatar.py

Output: 51a8a50f889c4706e8e5d27a8b1caaf2

**Comment by irl** [comment]
You can close this once you have merged #34 as I have already integrated your code snippet into that pull request.

**Comment by irl** [comment]
This is now resolved, as was present in the code that I wrote for the web interface skeleton using the snippet from @Jaminy.
